#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TFVARS_FILE="$SCRIPT_DIR/terraform.tfvars"

# ---------- helpers ----------
info()  { printf '\033[1;34m[INFO]\033[0m  %s\n' "$*"; }
warn()  { printf '\033[1;33m[WARN]\033[0m  %s\n' "$*"; }
error() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

generate_password() {
  # 24-char password: alphanumeric + special chars, ensuring complexity
  local pw
  pw="$(openssl rand -base64 32 | tr -d '/+=' | head -c 20)"
  # Append guaranteed special + digit + uppercase to satisfy SQL Server requirements
  pw="${pw}A1@x"
  echo "$pw"
}

generate_secret() {
  # 48-char alphanumeric secret for JWT
  openssl rand -base64 64 | tr -d '/+=' | head -c 48
}

# ---------- preflight checks ----------
for cmd in terraform az openssl; do
  command -v "$cmd" >/dev/null 2>&1 || error "'$cmd' is required but not found in PATH"
done

# Verify Azure CLI login
az account show >/dev/null 2>&1 || error "Not logged in to Azure CLI. Run 'az login' first."

ACCOUNT_NAME="$(az account show --query name -o tsv)"
SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
info "Using Azure subscription: $ACCOUNT_NAME ($SUBSCRIPTION_ID)"

# ---------- generate or reuse tfvars ----------
if [[ -f "$TFVARS_FILE" ]]; then
  info "Found existing terraform.tfvars — reusing it"
  warn "Delete terraform.tfvars and re-run to regenerate secrets"
else
  info "Generating secrets and creating terraform.tfvars..."

  SQL_PASSWORD="$(generate_password)"
  JWT_SECRET="$(generate_secret)"
  ADMIN_PASSWORD="$(generate_password)"

  cat > "$TFVARS_FILE" <<EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# This file contains sensitive values — do NOT commit it to git.

project_name = "devquiz"
location     = "norwayeast"
environment  = "prod"

sql_admin_username = "sqladmin"
sql_admin_password = "$SQL_PASSWORD"

jwt_secret     = "$JWT_SECRET"
admin_password = "$ADMIN_PASSWORD"

ghcr_image      = "ghcr.io/mamk95/devquiz"
app_service_sku = "S1"
EOF

  info "Created terraform.tfvars with generated secrets"
fi

# ---------- terraform init ----------
cd "$SCRIPT_DIR"
info "Running terraform init..."
terraform init -upgrade

# ---------- terraform plan ----------
info "Running terraform plan..."
terraform plan -out=tfplan

# ---------- confirm apply ----------
echo ""
read -rp "Apply this plan? (y/N): " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  info "Aborted. Plan saved to tfplan — apply later with: terraform apply tfplan"
  exit 0
fi

# ---------- terraform apply ----------
info "Applying..."
terraform apply tfplan
rm -f tfplan

# ---------- output summary ----------
echo ""
info "Deployment complete!"
echo ""
terraform output
echo ""
info "App Service URL: https://$(terraform output -raw app_service_hostname)"
info "Staging URL:     https://$(terraform output -raw app_service_staging_hostname)"
